---
- name: DoES Liverpool doorbot on a Raspberry Pi
  hosts: doorbot3-pi
  vars:
    pi_name: doorbot3
    ansible_port: 2225
  remote_user: pi
  become: yes
  become_method: sudo
  roles:
    - { role: base-doorbot, pi_name="doorbot3" }

  pre_tasks:
    - name: Update apt
      apt: upgrade=dist update_cache=yes
      become: true

  tasks:
    # FIXME Need to add the Kindle integration at some point
    - name: Reboot the pi to check it comes up cleanly
      command: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
