---
- name: Change SSH port on DoES Liverpool doorbot4
  hosts: doorbot4-pi
  vars:
    pi_name: doorbot4
    new_ssh_port: 2226
  remote_user: pi
  become: yes
  become_method: sudo

  handlers:
    - name: restart ssh
      action: service name=sshd state=restarted

  tasks:
    - name: Change the default password
      user: name=pi password="{{ pi_password }}"
    - name: Change the ssh port
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^Port"
        line: "Port {{ new_ssh_port }}"
      notify: restart ssh

